# -*- coding: utf-8 -*-
"""dashboard

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xYpwtcaoZXS4yZeuDwotkW649_lhqnAE
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import numpy as np
import streamlit as st
from PIL import Image
from babel.numbers import format_currency
sns.set(style='dark')

def year11(df,col):
  col=pd.to_datetime(col, infer_datetime_format=True)
  df= df.set_index('dteday')
  day11=df.loc['2011']
  return day11

def year12(df,col):
  col=pd.to_datetime(col, infer_datetime_format=True)
  df= df.set_index('dteday')
  day12=df.loc['2012']
  return day12

def byw(df):
    weather = df.resample(rule='M', on='mnth').agg({
        "registered": "sum",
        "cnt": "sum",
        "casual": "sum"
    })
    weather = weather.reset_index()
    weather.rename(columns={
    'registered': 'Registered',
    'cnt': 'tal',
    'casual': 'Casual UsersTo',
    },inplace=True)

    return weather

def bym(df):
  df.index=df.index.strftime('%B')
  df.rename(columns={
    'registered': 'Registered',
    'cnt': 'Total Rental',
    'casual': 'Casual Users',
  },inplace=True)

  dfm=df.groupby('mnth').agg({
    'Registered': 'sum',
    'Total': 'sum',
    'Casual Users': 'sum'
  }).round(0)

  return dfm

def month(df):
  date=df.dteday.unique()
  return date

df_day=pd.read_csv("/content/day.csv")
print(df_day)

def impute_outliers_IQR(df):
   q1=df.quantile(0.25)
   q3=df.quantile(0.75)
   IQR=q3-q1

   upper = df[~(df>(q3+1.5*IQR))].max()
   lower = df[~(df<(q1-1.5*IQR))].min()

   df = np.where(df > upper,
       df.mean(),
       np.where(
           df < lower,
           df.mean(),
           df
           )
       )
   return df

df_day['windspeed']=impute_outliers_IQR(df_day['windspeed'])
df_day['casual']=impute_outliers_IQR(df_day['casual'])
df_day['hum']=impute_outliers_IQR(df_day['hum'])

df_day['dteday']=pd.to_datetime(df_day['dteday'], infer_datetime_format=True)
df_day= df_day.set_index('dteday')
print(df_day.dtypes)

day_2011=df_day.loc['2011']
day_2012=df_day.loc['2012']

day_2011.rename(columns={
    'registered': 'Registered',
    'cnt': 'Total',
    'casual': 'Casual',
}, inplace=True)

day_2012.rename(columns={
    'registered': 'Registered',
    'cnt': 'Total',
    'casual': 'Casual',
}, inplace=True)

"""VISUALISASI DATA"""

#line chart

day_2011.index=day_2011.index.strftime('%B')
day_2011=day_2011.reset_index()
day_2012=day_2012.reset_index()
month=day_2011.dteday.unique()

df11 = day_2011.groupby('mnth').agg({
    'Registered': 'sum',
    'Total': 'sum',
    'Casual': 'sum'
}).round(0)

df12 = day_2012.groupby('mnth').agg({
    'Registered': 'sum',
    'Total': 'sum',
    'Casual': 'sum'
}).round(0)

d2011=df_day.iloc[:355,:]
d2011=d2011.reset_index()
d2012=df_day.iloc[355:,:]
d2012=d2012.reset_index()


w11=d2011.groupby(by='weathersit').agg({
    'registered': 'sum',
    'cnt': 'sum',
    'casual': 'sum',
}).round(0)
w11=w11.reset_index()
w11.loc[len(w11.index)]=[4,0,0,0]
w11['weathersit']=w11['weathersit'].replace([1,2,3,4],
 ['Clear Day','Mist/Cloudy', "Light Rain/Snow", 'Heavy Rain/Snow'])

w12=d2012.groupby(by='weathersit').agg({
    'registered': 'sum',
    'cnt': 'sum',
    'casual': 'sum',
}).round(0)
w12=w12.reset_index()
w12.loc[len(w12.index)]=[4,0,0,0]
w12['weathersit']=w12['weathersit'].replace([1,2,3,4],
 ['Clear Day','Mist/Cloudy', "Light Rain/Snow", 'Heavy Rain/Snow'])

with st.sidebar:
    logo = Image.open("/content/logo.png")
    st.image(logo, caption="Source: EmojiTerra")

st.title('Bike Rental Dashboard :bike:')

tab1,tab2=st.tabs(['2011','2012'])
with tab1:
  st.header('Bike Rental Summary')
  st.subheader("Daily Rental Usage")
  st.write('Bike sharing systems are new generation of traditional bike rentals where whole process from membership, rental and return back has become automatic. Through these systems, user is able to easily rent a bike from a particular position and return back at another position.')
  st.write('According to Springer Berling Heidelberg [2013], the characteristic of bike rental in 2011 and 2012 are quite similar as they share the same pattern over the year.')

  col1,col2 =st.columns(2)
  with col1:
    reg=df11['Registered'].sum()
    st.metric('Total Registered Bike', value=reg)
  with col2:
    rental=df11['Total'].sum()
    st.metric('Rental', value=rental)

  ##number od rental for 2011 and 2012
  fig, ax = plt.subplots(figsize=(16, 8))
  plt.plot(month, df11["Total"], marker='o', linewidth=2, label="2011", color="lightsteelblue")
  plt.plot(month, df12["Total"], marker='o', linewidth=2, label="2012", color="lightslategray")
  plt.title("Number of Rental 2011 and 2012", loc="center", fontsize=20)
  plt.xticks(fontsize=10)
  plt.yticks(fontsize=10)
  plt.legend()
  plt.show()

  ax.tick_params(axis='y', labelsize=20)
  ax.tick_params(axis='x', labelsize=15)
  ax.legend()
  st.pyplot(fig)

  st.write('The following graph shows the amount of bike rental every day for a year.  It can be concluded that bike rental is very volatile in 2012. There is an increase in the first half of the year, followed by a significant decline in the last months of the year.')


  ##linechart for number of rental 2011
  fig1, ax = plt.subplots(figsize=(16, 8))
  plt.plot(d2011['dteday'], d2011["cnt"], linewidth=2, label="2011", color="lightsteelblue")
  plt.title("Number of Rental 2011", loc="center", fontsize=15)
  plt.xticks(fontsize=10)
  plt.yticks(fontsize=10)
  plt.show()
  st.pyplot(fig1)

  st.subheader('Rental Usage Based on Weather')

  fig2, ax=plt.subplots(figsize=(16,8))
  sns.barplot(data=w11.melt(id_vars='weathersit',
                                    value_name='Count', var_name='Type'),
              x='weathersit', y='Count', hue='Type')
  plt.title("Bike Rental Count Based on Weather in 2011", loc="center", fontsize=11)
  plt.show()
  st.pyplot(fig2)
  st.write('The graphic above shows that people tend to use a bike during a clear, sunny day compared to a harsh weather such as raining or snowing. There is a significant different present in the graph where the number of people who bike during the harsh weather is zero')
  st.write('This graph also explain the bike rental decline during Octoboer-Frebruary, during winter people are rarely renting a bike. It is a very rare occurance that renting a bike in winter season is less than 10 times.')

with tab2:
  st.header('Bike Rental Summary')
  st.subheader("Daily Rental Usage")
  st.write('Bike sharing systems are new generation of traditional bike rentals where whole process from membership, rental and return back has become automatic. Through these systems, user is able to easily rent a bike from a particular position and return back at another position.')
  st.write('According to Springer Berling Heidelberg [2013], the characteristic of bike rental in 2011 and 2012 are quite similar as they share the same pattern over the year.')

  col1,col2 =st.columns(2)
  with col1:
    reg=df12['Registered'].sum()
    st.metric('Total Registered Bike', value=reg)
  with col2:
    rental=df12['Total'].sum()
    st.metric('Rental', value=rental)

  fig, ax = plt.subplots(figsize=(16, 8))
  plt.plot(month, df11["Total"], marker='o', linewidth=2, label="2011", color="lightsteelblue")
  plt.plot(month, df12["Total"], marker='o', linewidth=2, label="2012", color="lightslategray")
  plt.title("Number of Rental 2011 and 2012", loc="center", fontsize=20)
  plt.xticks(fontsize=10)
  plt.yticks(fontsize=10)
  plt.legend()
  plt.show()

  ax.tick_params(axis='y', labelsize=20)
  ax.tick_params(axis='x', labelsize=15)
  ax.legend()
  st.pyplot(fig)


  st.write('The following graph shows the amount of bike rental every day for a year.  It can be concluded that bike rental is very volatile in 2012. There is an increase in the first half of the year, followed by a significant decline in the last months of the year.')

  ##linechart for number of rental 2011
  fig1, ax = plt.subplots(figsize=(16, 8))
  plt.plot(d2012['dteday'], d2012["cnt"], linewidth=2, label="2012", color="lightslategray")
  plt.title("Number of Rental 2012", loc="center", fontsize=15)
  plt.xticks(fontsize=10)
  plt.yticks(fontsize=10)
  plt.show()
  st.pyplot(fig1)

  ##barplot based on weather
  st.subheader('Rental Usage Based on Weather')

  fig2, ax=plt.subplots(figsize=(16,8))
  sns.barplot(data=w12.melt(id_vars='weathersit',
                                    value_name='Count', var_name='Type'),
              x='weathersit', y='Count', hue='Type')
  plt.title("Bike Rental Count Based on Weather in 2012", loc="center", fontsize=11)
  plt.show()
  st.pyplot(fig2)
  st.write('The graphic above shows that people tend to use a bike during a clear, sunny day compared to a harsh weather such as raining or snowing. There is a significant different present in the graph where the number of people who bike during the harsh weather is zero.')
  st.write('This graph also explain the bike rental decline during Octoboer-Frebruary, during winter people are rarely renting a bike. It is a very rare occurance that renting a bike in winter season is less than 10 times.')